#define GIT_REV "@PLEX_CURRENT_DATE@-@PLEX_GIT_REVISION@"
#define PLEX_VERSION "@PLEX_VERSION_STRING@"
#define PLEX_VERSION_WIDE L"@PLEX_VERSION_STRING@"
#define PLEX_VERSION_SHORT "@PLEX_VERSION_STRING_SHORT@"
#define PLEX_WINDOWS_VERSION @PLEX_WINDOWS_VERSION@